### ISSUE TITLE
Let users choose what map marker they want

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/CB-Frontend#14]
I love the new map markers with the images, but it would be nice if users can still optionally use their custom map markers.

**Comment by kmohrf** [comment]
see: https://github.com/wielebenwir/CB-Frontend/blob/main/docs/configuration.md

**Comment by kmohrf** [comment]
Also: the app respects the configuration. Meaning: If a user uploaded a custom icon in wordpress this should still work as expected.  See: https://github.com/wielebenwir/CB-Frontend/blob/v0.1.0-alpha.4/src/commons-search/index.ts#L57-L69
