### ISSUE TITLE
Custom Map Markers for different item categories

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/CB-Frontend#15]
It should be possible for users to set different custom markers for different taxonomies of items. Consider this map for example:

https://flotte-berlin.de/lastenrad-ausleihen/standorte/bezirke/

Here they get assigned a different color value (I think the icon is colored in). Maybe it is best if we rather let users choose multiple icons for different taxonomies. In that regard they are not just limited to choosing different colors.

**Comment by kmohrf** [comment]
This is already possible :)
The question is: how can we make it configurable for users?

I’ll try to add some documentation.

**Comment by kmohrf** [comment]
see: https://github.com/wielebenwir/CB-Frontend/blob/main/docs/configuration.md
