### ISSUE TITLE
Button "clear all filters"

### ISSUE THREAD

**Issue by hansmorb** [wielebenwir/CB-Frontend#7]
It would be nice to have a button with which we could clear all filters and display all items again.

**Comment by kmohrf** [comment]
Now that #8 is implemented, do you think we still need that? Disabling active filters is pretty easy now.

**Comment by hansmorb** [comment]
Yes, looks great!

**Comment by kmohrf** [comment]
Re-opening this, because @chriwen liked the idea of a global reset button (at least in the filter panel) :)
